INSERT INTO Shed (title, description, price, createdAt, updatedAt) VALUES
('Cozy Pine Cabin', 'Rustic cabin surrounded by pine trees with a beautiful mountain view', 125.00, DATETIME('now'), DATETIME('now')),
('Lakeside Retreat', 'Modern shed house right on Lake Tahoe with private dock', 200.00, DATETIME('now'), DATETIME('now')),
('Forest Haven', 'Secluded wooden cabin in the heart of the forest', 95.00, DATETIME('now'), DATETIME('now')),
('Mountain View Shed', 'Minimalist shed with panoramic mountain views', 85.00, DATETIME('now'), DATETIME('now')),
('Riverside Cabin', 'Spacious cabin next to a rushing river', 150.00, DATETIME('now'), DATETIME('now')),
('Desert Oasis', 'Modern desert retreat with stunning sunset views', 175.00, DATETIME('now'), DATETIME('now')),
('Tiny House Dream', 'Compact but luxurious tiny house experience', 110.00, DATETIME('now'), DATETIME('now')),
('Redwood Escape', 'Elevated cabin among ancient redwood trees', 165.00, DATETIME('now'), DATETIME('now')),
('Garden Shed Suite', 'Charming converted shed in a flowering garden', 75.00, DATETIME('now'), DATETIME('now')),
('Alpine Lodge', 'Classic mountain lodge with ski-in access', 225.00, DATETIME('now'), DATETIME('now')),
('Beach Bungalow', 'Cozy bungalow steps from the ocean', 195.00, DATETIME('now'), DATETIME('now')),
('Writers Retreat', 'Quiet shed perfect for creative getaways', 90.00, DATETIME('now'), DATETIME('now')),
('Glacier View Cabin', 'Stunning cabin with views of glacier peaks', 180.00, DATETIME('now'), DATETIME('now')),
('Urban Micro Cabin', 'Modern micro cabin in the city', 135.00, DATETIME('now'), DATETIME('now')),
('Farmland Cottage', 'Restored farm shed on working organic farm', 115.00, DATETIME('now'), DATETIME('now')),
('Desert Modern', 'Architectural gem in the high desert', 250.00, DATETIME('now'), DATETIME('now')),
('Lake Cottage', 'Classic lake house with private beach', 165.00, DATETIME('now'), DATETIME('now')),
('Mountain Studio', 'Artist studio converted to modern living space', 95.00, DATETIME('now'), DATETIME('now')),
('Forest Treehouse', 'Elevated treehouse with modern amenities', 145.00, DATETIME('now'), DATETIME('now')),
('Valley Vista', 'Panoramic views of the Shenandoah Valley', 135.00, DATETIME('now'), DATETIME('now')),
('Coastal Hideaway', 'Secluded cabin on the Pacific coast', 175.00, DATETIME('now'), DATETIME('now')),
('Prairie Cabin', 'Peaceful cabin surrounded by wildflowers', 105.00, DATETIME('now'), DATETIME('now')),
('Mountain Micro', 'Tiny mountain cabin with huge views', 85.00, DATETIME('now'), DATETIME('now')),
('Desert Casita', 'Southwest style guest house', 125.00, DATETIME('now'), DATETIME('now')),
('Woodland Retreat', 'Cozy cabin in dense woodland', 115.00, DATETIME('now'), DATETIME('now')),
('Bayou Cabin', 'Authentic cabin on the bayou', 135.00, DATETIME('now'), DATETIME('now')),
('Canyon Overlook', 'Modern shed with red rock views', 155.00, DATETIME('now'), DATETIME('now')),
('Island Bungalow', 'Tropical tiny house near the beach', 165.00, DATETIME('now'), DATETIME('now')),
('Ranch Cabin', 'Rustic cabin on working cattle ranch', 145.00, DATETIME('now'), DATETIME('now')),
('Volcano View', 'Modern cabin with volcanic landscape views', 195.00, DATETIME('now'), DATETIME('now')); 